version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test_db
    container_name: test_db
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - 5432

volumes:
  db:
